on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn
    - run: yarn build
    - run: yarn test
